# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 083557260610e0058b3ae6ad5e6bd38a0201582e8b8be8dc5b052ceed5b85862377a437d35840983286ae1abe57d6b8370fc2b877075ae10ac2f6fc093654037

test:
  secret_key_base: 15ce568fcf28121f45b49af94031866d1dd5ffaeb6dfdead1395fce7b459aa23b5498cbaf0dd9d89233fbf6e426b84d3b93af26b594de2db7e93a5aca09dbda1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
